gateways:
  local_duckdb:
    connection:
      type: duckdb
      database: ./stock_lakehouse.db
      # Thực thi các lệnh này mỗi khi kết nối DuckDB để trỏ tới MinIO S3
      pre_statements:
        - "INSTALL httpfs; LOAD httpfs;"
        - "SET s3_endpoint='{{ env_var('S3_ENDPOINT') }}';"
        - "SET s3_access_key_id='{{ env_var('AWS_ACCESS_KEY_ID') }}';"
        - "SET s3_secret_access_key='{{ env_var('AWS_SECRET_ACCESS_KEY') }}';"
        - "SET s3_use_ssl=false;"
        - "SET s3_url_style='path';"
        - "SET s3_region='us-east-1';"

default_gateway: local_duckdb

model_defaults:
  dialect: duckdb
  owner: data_engineering_team