#!/bin/bash
set -e

# Tạo user với password từ env vars
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER $HUNGPHAM_USER WITH PASSWORD '$HUNGPHAM_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $HUNGPHAM_USER;
CREATE SCHEMA IF NOT EXISTS private AUTHORIZATION $HUNGPHAM_USER;
EOSQL