version: 1
disable_existing_loggers: false
formatters:
  default:
    format: '{"time":"%(asctime)s", "level":"%(levelname)s", "message":"%(message)s", "caller":"%(pathname)s:%(lineno)d"}'
    datefmt: "%Y-%m-%dT%H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
  file_debug:
    class: logging.handlers.RotatingFileHandler
    filename: shared/logger/logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    formatter: default
    level: DEBUG
  file_info:
    class: logging.handlers.RotatingFileHandler
    filename: shared/logger/logs/info.log
    maxBytes: 10485760
    backupCount: 3
    formatter: default
    level: INFO
  # Thêm cho warning, error
loggers:
  etl_platforms_ingestion_cophieu68_extract:
    level: DEBUG
    handlers: [console, file_debug]
    propagate: false
  etl_platforms_processing_dbt_models:
    level: INFO
    handlers: [console, file_info]
    propagate: false
  root:
    level: INFO
    handlers: [console]